using Content.Shared._OuterHorizons.ShuttleConsole;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._OuterHorizons.ShuttleConsole;

[GenerateTypedNameReferences]
public sealed partial class ThrusterInfoEntry : PanelContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public ThrusterInfoEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public ThrusterUnitData Data { get; private set; }

    public void SetState(ThrusterUnitData data)
    {
        Data = data;
        var entity = _entManager.GetEntity(data.ThrusterEntity);
        ThrusterView.WorldRotation = data.Direction.ToAngle();
        ThrusterView.SetEntity(entity);

        InfoLabelsContainer.Children.Clear();

        var tempColor = GetColorOfTemp(data.ThrusterTemperature, data.ThrusterHeatDamageThreshold);

        Temperature.Value = data.ThrusterTemperature;
        Temperature.Modulate = tempColor;

        var temperatureText = $"{Math.Round(TemperatureHelpers.KelvinToCelsius(data.ThrusterTemperature))} C";

        if(data.ThrusterHeatDamageThreshold is not null)
        {
            Temperature.Visible = true;

            temperatureText +=
                $" / {Math.Round(TemperatureHelpers.KelvinToCelsius(data.ThrusterHeatDamageThreshold.Value))} C";

            Temperature.MaxValue = data.ThrusterHeatDamageThreshold.Value;
        }
        else
        {
            Temperature.Visible = false;
        }

        AddDataInfo("Temperature",
            temperatureText,
            tempColor);

        AddDataInfo("Pressure",
            $"{Math.Round(data.InletPressure)}",
            Color.FromHex("#4bb2b5"));
    }


    private Color GetColorOfTemp(float temperature, float? maxTemp)
    {
        if(maxTemp is null)
            return Color.FromHex("#4bb2b5");

        var percent = temperature / maxTemp.Value * 100;

        if(percent < 70) return Color.FromHex("#4bb2b5");
        if(percent < 85) return Color.Orange;
        return Color.Red;
    }

    private void AddDataInfo(string name, string value, Color? color)
    {
        color ??= Color.FromHex("#4bb2b5");

        var mainPanel = new PanelContainer();
        mainPanel.PanelOverride = new StyleBoxFlat()
        {
            BorderColor = color.Value,
            BorderThickness = new Thickness(2),
        };

        mainPanel.HorizontalExpand = true;

        var labelPanel = new PanelContainer();
        labelPanel.PanelOverride = new StyleBoxFlat(color.Value);

        var nameLabel = new Label()
        {
            Text = name,
            Modulate = new Color(0f, 0f, 0f),
            Margin = new Thickness(4),
            HorizontalAlignment = HAlignment.Center,
        };

        nameLabel.AddStyleClass("ConsoleText");
        labelPanel.AddChild(nameLabel);

        var boxContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 10,
            HorizontalExpand = true,
        };

        mainPanel.AddChild(boxContainer);

        boxContainer.AddChild(labelPanel);

        var valueLabel = new Label()
        {
            Text = value,
            Margin = new Thickness(4),
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        };
        valueLabel.AddStyleClass("ConsoleText");
        boxContainer.AddChild(valueLabel);

        InfoLabelsContainer.AddChild(mainPanel);
    }
}
