using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.ResourceManagement;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            // OH14-Changes start, new lobby UI
            SetAnchorPreset(Parallax, LayoutPreset.Wide);
            // OH14-Changes end, new lobby UI
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            // OH14-Changes start, new lobby UI
            // CollapseButton.OnPressed += _ => TogglePanel(false);
            // ExpandButton.OnPressed += _ => TogglePanel(true);
            // OH14-Changes end, new lobby UI
        }

        public void SwitchState(LobbyGuiState state)
        {
            New_MainBox.Visible = false; // OH14-Changes
            CharacterSetupState.Visible = false; // OH14-Changes

            switch (state)
            {
                case LobbyGuiState.Default:
                    // OH14-Changes start, new lobby UI
                    New_MainBox.Visible = true;
                    // RightSide.Visible = true;
                    // OH14-Changes end, new lobby UI
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) New_MainBox.PixelWidth; // OH14-Changes
                    // OH14-Changes start, new lobby UI
                    // if (1 - (setupWidth / actualWidth) > 0.30)
                    // {
                    //     RightSide.Visible = false;
                    // }
                    // OH14-Changes end, new lobby UI
                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }
        // OH14-Changes start, new lobby UI
        // private void TogglePanel(bool value)
        // {
        //     RightSide.Visible = value;
        //     ExpandPanel.Visible = !value;
        // }
        // OH14-Changes end, new lobby UI
        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
