- type: playTimeTracker
  id: OH14_UcoRole

- type: playTimeTracker
  id: OH14_UcoCommanderRole

# Колонист

- type: job
  id: OH14_UcoRole
  name: Колонист
  description: Колонист, в бывшем на контракте с United Colonial Organization.
  playTimeTracker: OH14_UcoRole
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  setPreference: true
  startingGear: OH14_UcoGear
  access:
  - UCO

- type: startingGear
  id: OH14_UcoGear
  equipment:
    belt: OH14_ClothingBeltWaistbag
    # outerClothing: OH14_ClothingOuterCoatUco
    jumpsuit: OH14_ClothingJumpsuitUco
    pants: OH14_ClothingPantsBasic
    back: ClothingBackpackSatchelUco
    shoes: OH14_ClothingBoots
    id: OH14_PDAUCO
    pocket2: OH14_ClothingMaskGas
  storage:
    back:
    - OH14_CrowbarBasic
    - OH14_FlashlightFilled
    - OH14_OxygenTankWhiteFilled

# Коммандир

- type: job
  id: OH14_UcoCommanderRole
  name: Коммандир
  description: Глава поселения, по какойто причине выбранный экипажем.
  playTimeTracker: OH14_UcoCommanderRole
  # requirements:
  #   - !type:DepartmentTimeRequirement
  #     department: OH14_UcoDepartment
  #     time: 2h
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  setPreference: true
  startingGear: OH14_UcoCommanderGear
  access:
  - Security
  - UCO

- type: startingGear
  id: OH14_UcoCommanderGear
  equipment:
    belt: OH14_ClothingBeltWaistbag
    # outerClothing: OH14_ClothingOuterCoatUco
    jumpsuit: OH14_ClothingJumpsuitUCOCommander
    pants: OH14_ClothingPantsBasic
    back: ClothingBackpackSatchelUco
    shoes: OH14_ClothingBoots
    id: OH14_PDAUCOCommander
    pocket2: OH14_ClothingMaskGas
  storage:
    back:
    - OH14_Baton
    - OH14_CrowbarBasic
    - OH14_FlashlightFilled
    - OH14_OxygenTankWhiteFilled
